---
title: "Homework 1"
author: Eric Sun
output: html_document
---

This is my solution to HW1

```{r}
library(tidyverse)
```


## Problem 1

Create a data frame with the specified elements.

```{r}
prob1_df=
tibble(
  samp = rnorm(10),
  samp_gt_0 = samp > 0,
  char_vec = c("a", "b","c","d","e","f","g","h","i","j"),
  factor_vec=factor(c("low","low","low","mod","mod","mod","mod", "high","high","high"))
)
```
Take the mean of each variable in my data frame.
```{r}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_0))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, factor_vec))
```

I can take the mean of numbers and logical but not character or factor.
```{r}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```


```{r}
as.numeric(pull(prob1_df, samp_gt_0))*pull(prob1_df,samp)
```


## Problem 2

Loading penguins dataset
```{r}
data("penguins", package="palmerpenguins")
```

Describing penguins dataset
```{r}
str(penguins)
nrow(penguins)
ncol(penguins)
mean(pull(penguins,flipper_length_mm),na.rm=TRUE)
```

Scatterplot of flipper length vs bill length
```{r}
ggplot(penguins, aes(x=pull(penguins,bill_length_mm), y=pull(penguins,flipper_length_mm), color=pull(penguins,species))) + geom_point()
ggsave("problem1_scatterplot.pdf",height=4,width=4)
```

